version: '3.1'
services:
  elasticsearch:
    logging:
      driver: journald
      options:
        tag: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - discovery.zen.ping.unicast.hosts=tasks.elasticsearch,tasks.elasticsearch1,tasks.elasticsearch2
      - node.name=elasticsearch
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==swarm-manager1

  elasticsearch1:
    logging:
      driver: journald
      options:
        tag: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - discovery.zen.ping.unicast.hosts=tasks.elasticsearch,tasks.elasticsearch1,tasks.elasticsearch2
      - node.name=elasticsearch1
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==swarm-worker1

  elasticsearch2:
    logging:
      driver: journald
      options:
        tag: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - discovery.zen.ping.unicast.hosts=tasks.elasticsearch,tasks.elasticsearch1,tasks.elasticsearch2
      - node.name=elasticsearch2
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==swarm-worker2

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    ports:
      - 5601:5601
    logging:
      driver: journald
      options:
        tag: kibana
    networks:
      - esnet
    volumes:
      - kibanadata:/usr/share/kibana
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - node.hostname==swarm-manager1

  logstash:
    image: docker.elastic.co/logstash/logstash:6.8.0
    logging:
      driver: journald
      options:
        tag: logstash
    networks:
      - esnet
    volumes:
      - {/PATH/TO/DATA/DIR}:/usr/share/logstash/csvData
      - {/PATH/TO/CONF/FILE}:/usr/share/logstash/pipeline
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==swarm-manager1
    depends_on: [tasks.elasticsearch,tasks.elasticsearch1,tasks.elasticsearch2]

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  kibanadata:
    driver: local

networks:
  esnet: